adjusted workflow to be able run more then initial

diff --git a/.github/workflows/deploy_argocd.yaml b/.github/workflows/deploy_argocd.yaml
--- a/.github/workflows/deploy_argocd.yaml
+++ b/.github/workflows/deploy_argocd.yaml
@@ -78,14 +78,46 @@ jobs:
       - name: Forward ArgoCD server port
         run: kubectl port-forward svc/argocd-server -n argocd 8080:443 &
     
-      - name: Login to ArgoCD
+      - name: Attempt ArgoCD Login
+        id: login_attempt
         env:
           ARGOCD_PASSWORD: ${{ steps.argocd_password.outputs.password }}
         run: |
           if [ -n "$ARGOCD_PASSWORD" ]; then
-            argocd login localhost:8080 --username admin --password "$ARGOCD_PASSWORD" --insecure --grpc-web
+            if argocd login localhost:8080 --username admin --password "$ARGOCD_PASSWORD" --insecure --grpc-web; then
+              echo "ArgoCD login successful."
+              echo "::set-output name=login_successful::true"
+            else
+              echo "ArgoCD login failed with initial password."
+              echo "::set-output name=login_successful::false"
+            fi
           else
             echo "ArgoCD login skipped due to missing password."
+            echo "::set-output name=login_successful::false"
+          fi
+
+          - name: Fetch ArgoCD password from AWS Secrets Manager
+          if: steps.login_attempt.outputs.login_successful == 'false'
+          id: get_password
+          run: |
+            SECRET=$(aws secretsmanager get-secret-value --secret-id argocd-password --query SecretString --output text --region ${{ vars.AWS_REGION }})
+            echo "::set-output name=secret_password::$SECRET"
+  
+      - name: Retry ArgoCD Login with AWS Secret
+        if: steps.login_attempt.outputs.login_successful == 'false'
+        env:
+          ARGOCD_SECRET_PASSWORD: ${{ steps.get_password.outputs.secret_password }}
+        run: |
+          if [ -n "$ARGOCD_SECRET_PASSWORD" ]; then
+            if argocd login localhost:8080 --username admin --password "$ARGOCD_SECRET_PASSWORD" --insecure --grpc-web; then
+              echo "ArgoCD login successful with password from AWS Secrets Manager."
+            else
+              echo "ArgoCD login failed with AWS Secrets Manager password."
+              exit 1
+            fi
+          else
+          echo "No password retrieved from AWS Secrets Manager. Exiting."
+          exit 1
           fi
 
       - name: Register EKS Cluster with ArgoCD
